### ISSUE TITLE
Package fails to build with Xcode 14 beta (14A5228q)

### ISSUE THREAD

**Issue by orj** [unsignedapps/Vexil#104]
The package fails to build in Xcode 14 beta (14A5228q).  It crashes the compiler with:

```
Malformed rewrite rule: τ_0_0.[OptionalFlagValue:WrappedFlagValue].[CaseIterable:AllCases].[RandomAccessCollection:Element] => τ_0_0.[OptionalFlagValue:WrappedFlagValue].[CaseIterable] [lhs↓] [rhs↓]
&&& symbol.getKind() != Symbol::Kind::Protocol
```

I've filed "Feedback" as FB10217668.

**Vexil version:** 2.2.0
**Swift version:** swift-driver version: 1.55.1 Apple Swift version 5.7 (swiftlang-5.7.0.113.202 clang-1400.0.16.2)
**Environment:** Xcode 14 beta (14A5228q)

### ✅ Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/unsignedapps/Vexil/issues)

### 🔢 Steps to Reproduce

Attempt to build the package with Xcode 14 beta (14A5228q).

### 🎯 Expected behavior

The package compiles.

### 🕵️‍♀️ Actual behavior

The Swift compiler crashes.

**Comment by bok-** [comment]
This was an issue with Swift that was fixed in https://github.com/apple/swift/pull/59557
